# Pulling Nginx image from docker hub
image:
  repository: nginx
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: <DOMAIN>
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
  - secretName: cert-secret
    hosts:
      - <DOMAIN>

# Service Port configuration
service:
  type: ClusterIP
  port: 80

# Resource configuration
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Autoscaling configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

