apiVersion: v1
kind: Service
metadata:
  name: {{ include "custom-chart.fullname" . }}
  labels:
    {{- include "custom-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - targetPort: {{ .Values.service.port }}
      port: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "custom-chart.selectorLabels" . | nindent 4 }}
