apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: <EMAIL>
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert-services
spec:
  commonName: <DOMAIN>
  dnsNames:
  - <DOMAIN>
  issuerRef:
    kind: Issuer
    name: letsencrypt
  secretName: cert-secret